var arrStack = require('./_ArrStack');
var listStack = require('./_SLStack');
var arrStack1 = new arrStack();
var listStack1 = new listStack();

console.log("Array Stack isEmpty?: ", arrStack1.isEmpty());
console.log("List Stack isEmpty?: ", listStack1.isEmpty());
console.log("-------------------------------------------------");
console.log("Stack contains?: ", arrStack1.contains1(10));
console.log("Stack contains?: ", arrStack1.contains2(10));
console.log("List Stack contains?: ", listStack1.contains(10));
console.log("-------------------------------------------------");
console.log("Stack size: ", arrStack1.size());
console.log("List Stack size: ", listStack1.size());
console.log("-------------------------------------------------");
console.log("Stack push: ", arrStack1.push(10));
console.log("Stack push: ", arrStack1.push(20));
console.log("Stack push: ", arrStack1.push(30));
console.log("Stack push: ", arrStack1.push(40));
console.log("List Stack push: ", listStack1.push(10));
console.log("List Stack push: ", listStack1.push(20));
console.log("List Stack push: ", listStack1.push(30));
console.log("List Stack push: ", listStack1.push(40));
console.log("-------------------------------------------------");
console.log("Stack values: ", arrStack1.SLSdisplay());
console.log("List Stack values: ", listStack1.SLSdisplay());
console.log("-------------------------------------------------");
console.log("-------------------------------------------------");
console.log("Array Stack isEmpty?: ", arrStack1.isEmpty());
console.log("List Stack isEmpty?: ", listStack1.isEmpty());
console.log("-------------------------------------------------");
console.log("Stack size: ", arrStack1.size());
console.log("List Stack size: ", listStack1.size());
console.log("-------------------------------------------------");
console.log("Stack contains?: ", arrStack1.contains1(10));
console.log("Stack contains?: ", arrStack1.contains2(10));
console.log("List Stack contains?: ", listStack1.contains(10));
console.log("-------------------------------------------------");
console.log("Stack contains?: ", arrStack1.contains1(100));
console.log("Stack contains?: ", arrStack1.contains2(100));
console.log("List Stack contains?: ", listStack1.contains(100));
console.log("-------------------------------------------------");
console.log("Stack top: ", arrStack1.top());
console.log("Stack pop: ", arrStack1.pop());
console.log("List Stack top: ", listStack1.top());
console.log("List Stack pop: ", listStack1.pop());
console.log("-------------------------------------------------");
console.log("Stack top: ", arrStack1.top());
console.log("Stack pop: ", arrStack1.pop());
console.log("List Stack top: ", listStack1.top());
console.log("List Stack pop: ", listStack1.pop());
console.log("-------------------------------------------------");
console.log("Stack top: ", arrStack1.top());
console.log("Stack pop: ", arrStack1.pop());
console.log("List Stack top: ", listStack1.top());
console.log("List Stack pop: ", listStack1.pop());
console.log("-------------------------------------------------");
console.log("Stack top: ", arrStack1.top());
console.log("Stack pop: ", arrStack1.pop());
console.log("List Stack top: ", listStack1.top());
console.log("List Stack pop: ", listStack1.pop());
console.log("-------------------------------------------------");
console.log("Stack top: ", arrStack1.top());
console.log("Stack pop: ", arrStack1.pop());
console.log("List Stack top: ", listStack1.top());
console.log("List Stack pop: ", listStack1.pop());
console.log("-------------------------------------------------");